[tool.poetry]
name = "test-workflow"
version = "0.1.0"
description = ""
authors = ["linglp <linglp@umich.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
